name: 0-Setup-Environment-Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    name: Configuración inicial (Windows)
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Crear estructura de directorios
        run: |
          mkdir -p src\edu_pad\static\db
          mkdir -p src\edu_pad\static\csv
          mkdir -p src\edu_pad\static\logs
        shell: cmd
          
      - name: Crear entorno virtual
        run: python -m venv venv
        
      - name: Activar entorno virtual
        run: .\venv\Scripts\activate
        shell: pwsh
        
      - name: Instalar dependencias con setup.py
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          # Instalar SQLite que no está en setup.py pero es necesario
          pip install sqlite3-simple
        shell: pwsh
          
      - name: Verificar instalación
        run: |
          python -c "import pandas; import requests; import openpyxl; from bs4 import BeautifulSoup; import sqlite3; print('Entorno configurado correctamente')"
        shell: pwsh
          
      - name: Preparar estructura del proyecto
        run: |
          # Copiar los archivos Python al directorio src/edu_pad
          copy database.py src\edu_pad\ 2>nul
          copy dataweb.py src\edu_pad\ 2>nul
          copy main_extractor.py src\edu_pad\ 2>nul
          copy main_ingesta.py src\edu_pad\ 2>nul
          copy monitor.py src\edu_pad\ 2>nul
          
          # Si no existen, crear archivos vacíos para evitar errores
          type nul > src\edu_pad\database.py
          type nul > src\edu_pad\dataweb.py
          type nul > src\edu_pad\main_extractor.py
          type nul > src\edu_pad\main_ingesta.py
          type nul > src\edu_pad\monitor.py
        shell: cmd
          
      - name: Guardar estructura del proyecto
        uses: actions/upload-artifact@v4
        with:
          name: project-structure-windows
          path: |
            src/
            setup.py
            venv/
          retention-days: 7