name: 2-Data-Ingestion

on:
  workflow_run:
    workflows: ["1-Data-Extraction"]
    types:
      - completed

jobs:
  ingest_data:
    name: Ingestar datos en SQLite
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Instalar dependencias con setup.py
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install sqlite3-simple
          
      - name: Descargar CSV desde artefactos
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 1-Data-Extraction.yml
          workflow_conclusion: success
          name: dolar-data-csv
          path: src/edu_pad/static/csv/
          
      - name: Verificar existencia del CSV
        id: check_csv
        run: |
          if [ -f "src/edu_pad/static/csv/data_extractor.csv" ]; then
            echo "csv_exists=true" >> $GITHUB_OUTPUT
            echo "CSV encontrado. Procediendo con la ingesta..."
          else
            echo "csv_exists=false" >> $GITHUB_OUTPUT
            echo "Error: CSV no encontrado"
            exit 1
          fi
          
      - name: Crear directorio de base de datos
        if: steps.check_csv.outputs.csv_exists == 'true'
        run: mkdir -p src/edu_pad/static/db
          
      - name: Ejecutar ingesta de datos
        if: steps.check_csv.outputs.csv_exists == 'true'
        run: python src/edu_pad/main_ingesta.py
        
      - name: Subir base de datos como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: dolar-sqlite-db
          path: src/edu_pad/static/db/dolar_analisis.db
          retention-days: 7
          
      - name: Limpiar archivos CSV
        if: steps.check_csv.outputs.csv_exists == 'true'
        run: |
          echo "Limpiando archivos CSV temporales..."
          rm -f src/edu_pad/static/csv/data_extractor.csv
          echo "Archivos CSV eliminados correctamente"